### ISSUE TITLE
build error: missing packages `gotype/engine/dom/styledtree/builder`

### ISSUE THREAD

**Issue by mewmew** [npillmayer/gotype#21]
While trying to build `gotype` (rev a446b8734d65ca0618b43e43e9e8d1faccdcbe4d) I run into the following build error:

```
$ go install -v ./...
gotype/cmd/style.go:64:2: cannot find package "github.com/npillmayer/gotype/engine/dom/styledtree/builder" in any of:
	/home/u/go/src/github.com/npillmayer/gotype/engine/dom/styledtree/builder (from $GOROOT)
	/home/u/goget/src/github.com/npillmayer/gotype/engine/dom/styledtree/builder (from $GOPATH)
	/home/u/Desktop/go/src/github.com/npillmayer/gotype/engine/dom/styledtree/builder
```

I know that the `syntax/gallery` package is marked as suspended. However, building `gotype` using `go install ./...` it currently generates the following build error:
```
syntax/gallery/interpreter.go:48:2: cannot find package "github.com/npillmayer/gotype/syntax/gallery/grammar" in any of:
	/home/u/go/src/github.com/npillmayer/gotype/syntax/gallery/grammar (from $GOROOT)
	/home/u/goget/src/github.com/npillmayer/gotype/syntax/gallery/grammar (from $GOPATH)
	/home/u/Desktop/go/src/github.com/npillmayer/gotype/syntax/gallery/grammar
```

To resolve the build error related to `syntax/gallery` I suggest either to remove the package entirely (as already noted in the readme `The package will probably be *removed* in the future.`), or alternatively, to add `//+build ignore` build tags to the `syntax/gallery` source files, so they are excluded from the build.

Cheers,
Robin

**Comment by npillmayer** [comment]
Hi Robin,

thank you for your interest in gotype!  I know the top level executable is currently unable to build.  Please note that the whole project is currently a big experiment and not suited for anything remotely productive.  Nevertheless, I’ll take a look at the issue and make it buildable again.  I recently changed a lot of interfaces and need to clean this up in the build of the top-level app.

A word about the gotype CLI: It is currently intended as an interactive testing driver only. That’s the reason I have postponed working on it: Currently I rely on unit tests only during a phase of heavy changes and refactoring. Please be patient until there’s something useful to have a CLI for in the first place :-)

All the best,

—Norbert

**Comment by npillmayer** [comment]
Code in gotype has been split and distributed to several modules.
The main typesetting experiment has moved to tyse.
